###########################################################################
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# imitations under the License.
###########################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.actions.job
  namespace: {{ .Release.Namespace }}
data:
  url-actions: |
    [
{{ if ne .Values.env.kubeEnv "minishift" }}      
      { 
        "name":"detail", 
        "text":"View Detail", 
        "text.nls":"action.url.job.detail.text", 
        "description":"View Job detail",
        "description.nls":"action.url.job.detail.desc",
{{ if eq .Values.env.kubeEnv "minikube" }}
        "url-pattern":"${builtin.openshift-console-url}/job/${resource.$.metadata.namespace}/${resource.$.metadata.name}?namespace=${resource.$.metadata.namespace}", 
{{ else if or (eq .Values.env.kubeEnv "okd") (eq .Values.env.kubeEnv "ocp") }} 
        "url-pattern":"${builtin.openshift-admin-console-url}/k8s/ns/${resource.$.metadata.namespace}/jobs/${resource.$.metadata.name}", 
{{ end }}
        "open-window": "current", 
        "menu-item": "false" 
      },
{{ end }}
      {
        "name":"joblogs",
        "text":"View Job Logs",
        "text.nls":"action.url.job.logs.text",
        "description":"View Job logs",
        "description.nls":"action.url.job.logs.desc",
        "url-pattern":"${builtin.openshift-console-url}/project/${resource.$.metadata.namespace}/browse/pods/${var.podname}?tab=logs",
        "open-window": "tab"
      }
    ],
  variables: |
    {
        "podname": "${func.kubectlGet(pods,-l,job-name=${resource.$.metadata.name},-o=jsonpath=${snippet.name()})}"

    }
  snippets:  |
    {
        "name": "function name() { return '{.items[*].metadata.name}'; }"
    }
